/* Data for the archive — illustrative, fictional-plausible */

const LOCOMOTIVES = [
  {
    id: "red-flag-1",
    class: "КРАСНЫЙ ФЛАГ 1",
    name: "Red Flag 1",
    kr: "붉은기 1호",
    type: "Electric mainline",
    typeKr: "전기기관차",
    year: 1961,
    builder: "Kim Chŏng-t'ae Electric Locomotive Works",
    builderKr: "김종태전기기관차공장",
    power: "2,700 kW",
    voltage: "3 kV DC",
    weight: "122 t",
    gauge: "1,435 mm",
    wheel: "Bo′Bo′Bo′",
    top: "100 km/h",
    built: 52,
    status: "Partially operational",
    plate: "LOCO-001",
    dek: "The first indigenously-built electric locomotive. A six-axle freight hauler derived in part from Soviet VL60 practice, modified for the steeper gradients of the P'yŏngra Line.",
    tags: ["electric", "freight", "1960s", "mainline"]
  },
  {
    id: "red-flag-5100",
    class: "КРАСНЫЙ ФЛАГ 5100",
    name: "Red Flag 5100",
    kr: "붉은기 5100호",
    type: "Electric mainline (mixed traffic)",
    typeKr: "전기기관차 (혼합)",
    year: 1974,
    builder: "Kim Chŏng-t'ae Works",
    builderKr: "김종태공장",
    power: "4,200 kW",
    voltage: "3 kV DC",
    weight: "138 t",
    gauge: "1,435 mm",
    wheel: "Bo′Bo′Bo′",
    top: "105 km/h",
    built: 210,
    status: "In service",
    plate: "LOCO-002",
    dek: "The workhorse of the national grid — seen hauling nearly every class of train from anthracite drags out of Anju to international services to Sinŭiju.",
    tags: ["electric", "freight", "passenger", "1970s"]
  },
  {
    id: "juche",
    class: "주체호",
    name: "Juche",
    kr: "주체호",
    type: "Diesel-hydraulic",
    typeKr: "디젤기관차",
    year: 1967,
    builder: "Wŏnsan Locomotive Factory",
    builderKr: "원산기관차공장",
    power: "1,470 kW",
    voltage: "—",
    weight: "104 t",
    gauge: "1,435 mm",
    wheel: "Co′Co′",
    top: "90 km/h",
    built: 38,
    status: "Reserve",
    plate: "LOCO-003",
    dek: "A diesel-hydraulic built for non-electrified branches in the east. Distinctive box cab, twin exhaust stacks, and a hand-painted red star on the nose.",
    tags: ["diesel", "branch", "1960s"]
  },
  {
    id: "kanghaenggun",
    class: "강행군호",
    name: "Kanghaenggun",
    kr: "강행군호",
    type: "Electric mainline",
    typeKr: "전기기관차",
    year: 1998,
    builder: "Kim Chŏng-t'ae Works",
    builderKr: "김종태공장",
    power: "4,800 kW",
    voltage: "3 kV DC",
    weight: "144 t",
    gauge: "1,435 mm",
    wheel: "Bo′Bo′Bo′",
    top: "110 km/h",
    built: 64,
    status: "In service",
    plate: "LOCO-004",
    dek: "Named for the 'Arduous March'. A heavy refit of the Red Flag 5100 with replacement traction motors and an enlarged dynamic-braking resistor bank.",
    tags: ["electric", "freight", "1990s"]
  },
  {
    id: "m62-k",
    class: "M62K",
    name: "M62 (Korean)",
    kr: "엠육십이호",
    type: "Diesel-electric",
    typeKr: "디젤전기기관차",
    year: 1976,
    builder: "Luhanskteplovoz (import)",
    builderKr: "루간스크 (수입)",
    power: "1,470 kW",
    voltage: "—",
    weight: "116 t",
    gauge: "1,435 mm",
    wheel: "Co′Co′",
    top: "100 km/h",
    built: 32,
    status: "In service",
    plate: "LOCO-005",
    dek: "Twenty-six single-cab and six double-cab M62s were delivered 1976–1984 via Tumangang. Used principally on the north-eastern Hambuk Line.",
    tags: ["diesel", "import", "1970s"]
  },
  {
    id: "sr-class",
    class: "СР급",
    name: "SR (Soviet-type)",
    kr: "SR급 증기기관차",
    type: "Steam 2-6-2",
    typeKr: "증기기관차",
    year: 1949,
    builder: "Voroshilovgrad / indigenous refit",
    builderKr: "보로실로프그라드",
    power: "1,600 ihp",
    voltage: "—",
    weight: "103 t (engine)",
    gauge: "1,435 mm",
    wheel: "2-6-2 (1E1)",
    top: "85 km/h",
    built: 18,
    status: "Preserved / heritage",
    plate: "LOCO-006",
    dek: "One of the last steam classes in regular freight service into the early 1980s. Two survive as static exhibits at Wŏnsan and Hamhŭng depots.",
    tags: ["steam", "heritage", "1940s"]
  },
  {
    id: "metro-d",
    class: "D-형",
    name: "Metro D-stock",
    kr: "평양지하철 D형",
    type: "Metro (ex-Berlin)",
    typeKr: "지하철 전동차",
    year: 1998,
    builder: "LEW Hennigsdorf (secondhand)",
    builderKr: "LEW (중고)",
    power: "440 kW/car",
    voltage: "825 V DC 3rd rail",
    weight: "30 t/car",
    gauge: "1,435 mm",
    wheel: "Bo′Bo′",
    top: "70 km/h",
    built: "~108 cars",
    status: "In service",
    plate: "LOCO-007",
    dek: "Ex-Berlin U-Bahn Gisela and Dora sets, purchased and refurbished for P'yŏngyang Metro. Re-liveried in deep maroon with cream banding.",
    tags: ["metro", "import", "1990s"]
  },
  {
    id: "metro-dprk",
    class: "김종태-2020",
    name: "Metro DPRK-built",
    kr: "김종태-2020형",
    type: "Metro (indigenous)",
    typeKr: "지하철 전동차",
    year: 2020,
    builder: "Kim Chŏng-t'ae Works",
    builderKr: "김종태공장",
    power: "560 kW/car",
    voltage: "825 V DC 3rd rail",
    weight: "34 t/car",
    gauge: "1,435 mm",
    wheel: "Bo′Bo′",
    top: "80 km/h",
    built: "16 sets",
    status: "In service",
    plate: "LOCO-008",
    dek: "First entirely domestic metro stock since the 1970s trials. Features LED roll-signs and an LCD route strip above each door.",
    tags: ["metro", "indigenous", "2020s"]
  }
];

const LINES = [
  { id: "pyongra", code: "평라", name: "P'yŏngra Line", kr: "평라선",  color: "var(--accent)", length: 781, stations: 56, opened: 1928, electrified: "1975–1983", traffic: "Heavy mixed", note: "P'yŏngyang → Rasŏn, trunk of the eastern network." },
  { id: "pyongbu", code: "평부", name: "P'yŏngbu Line", kr: "평부선",  color: "oklch(0.48 0.1 60)",  length: 187, stations: 24, opened: 1906, electrified: "1979", traffic: "Heavy mixed", note: "P'yŏngyang → Kaesŏng, connects to South Korean border." },
  { id: "pyongui", code: "평의", name: "P'yŏngŭi Line", kr: "평의선",  color: "var(--accent-2)", length: 225, stations: 29, opened: 1906, electrified: "1975", traffic: "Heavy passenger/intl.", note: "P'yŏngyang → Sinŭiju, gateway to China via Dandong." },
  { id: "manpo", code: "만포", name: "Manp'o Line",   kr: "만포선",   color: "oklch(0.55 0.08 160)",length: 299, stations: 40, opened: 1939, electrified: "1988", traffic: "Freight (ore, timber)", note: "Sunch'ŏn → Manp'o, mountainous." },
  { id: "hambuk", code: "함북", name: "Hambuk Line",  kr: "함북선",   color: "oklch(0.58 0.08 40)", length: 327, stations: 38, opened: 1924, electrified: "—", traffic: "Freight + local", note: "North-east coastal line, still diesel." },
  { id: "kangwon", code: "강원", name: "Kangwŏn Line", kr: "강원선",   color: "oklch(0.50 0.09 300)",length: 145, stations: 18, opened: 1914, electrified: "1983", traffic: "Mixed", note: "Koksan → Wŏnsan, scenic mountain traverse." },
  { id: "pyongdok", code: "평덕", name: "P'yŏngdŏk Line", kr: "평덕선", color: "oklch(0.52 0.06 220)", length: 192, stations: 24, opened: 1910, electrified: "1972", traffic: "Coal (anthracite)", note: "P'yŏngyang → Kujang, backbone of anthracite haulage." }
];

const STATIONS_FEATURED = [
  {
    id: "pyongyang",
    name: "P'yŏngyang Station",
    kr: "평양역",
    built: 1907,
    rebuilt: 1958,
    arch: "Socialist classical",
    archKr: "사회주의 고전",
    platforms: 8,
    linesServed: 6,
    area: "14,200 m²",
    note: "The central terminus. Twin clock towers, coffered ceiling in the main concourse, and a mural of Mt. Paektu above the ticket hall."
  },
  {
    id: "sinuiju",
    name: "Sinŭiju Ch'ŏngnyŏn",
    kr: "신의주청년역",
    built: 1911,
    rebuilt: 1988,
    arch: "Late Stalinist",
    archKr: "후기 스탈린 양식",
    platforms: 5,
    linesServed: 2,
    area: "6,800 m²",
    note: "Border station. Gauge-change pit for Chinese-bound stock; customs hall occupies the west wing."
  },
  {
    id: "kaesong",
    name: "Kaesŏng Station",
    kr: "개성역",
    built: 1912,
    rebuilt: 1950,
    arch: "Reconstructed colonial",
    archKr: "재건 근대식",
    platforms: 3,
    linesServed: 2,
    area: "2,400 m²",
    note: "Heavily damaged in 1950–53 and rebuilt in brick with a low gabled roof. Closest operational station to the DMZ."
  },
  {
    id: "chongjin",
    name: "Ch'ŏngjin Ch'ŏngnyŏn",
    kr: "청진청년역",
    built: 1927,
    rebuilt: 1975,
    arch: "Modernist slab",
    archKr: "근대주의",
    platforms: 6,
    linesServed: 3,
    area: "5,200 m²",
    note: "Serves the north-eastern port city. Distinctive cantilevered canopy running the full 220 m platform length."
  },
  {
    id: "rason",
    name: "Rasŏn Station",
    kr: "라선역",
    built: 1935,
    rebuilt: 2012,
    arch: "Contemporary",
    archKr: "현대식",
    platforms: 4,
    linesServed: 2,
    area: "3,100 m²",
    note: "Rebuilt as part of the special economic zone upgrade. Glass-curtain concourse, multilingual signage in Korean/Russian/Chinese."
  },
  {
    id: "puhung",
    name: "Puhŭng (Metro)",
    kr: "부흥역",
    built: 1987,
    rebuilt: "—",
    arch: "Subterranean palatial",
    archKr: "지하 궁전식",
    platforms: 2,
    linesServed: 1,
    area: "—",
    note: "Ch'ŏllima Line terminus. Known for its ten cut-glass chandeliers and a marble mosaic depicting the liberation of P'yŏngyang."
  }
];

const GLOSSARY = [
  { hangul: "기차", roman: "GICH'A", en: "train (general)", hanja: "汽車", note: "Lit. 'steam cart'." },
  { hangul: "렬차", roman: "RYŎLCH'A", en: "train (formal / DPRK usage)", hanja: "列車", note: "Preferred in North Korean usage; South Korean spelling: 열차." },
  { hangul: "기관차", roman: "GIGWANCH'A", en: "locomotive", hanja: "機關車", note: "" },
  { hangul: "전동차", roman: "CHŎNDONGCH'A", en: "EMU / multiple unit", hanja: "電動車", note: "Used for metro and urban rail." },
  { hangul: "전기기관차", roman: "CHŎN'GI-GIGWANCH'A", en: "electric locomotive", hanja: "電氣機關車", note: "" },
  { hangul: "증기기관차", roman: "CHŬNGGI-GIGWANCH'A", en: "steam locomotive", hanja: "蒸氣機關車", note: "" },
  { hangul: "객차", roman: "KAEKCH'A", en: "passenger coach", hanja: "客車", note: "" },
  { hangul: "화차", roman: "HWACH'A", en: "freight wagon", hanja: "貨車", note: "" },
  { hangul: "역", roman: "YŎK", en: "station", hanja: "驛", note: "Suffixed to proper names: 평양역 = P'yŏngyang Station." },
  { hangul: "역사", roman: "YŎKSA", en: "station building", hanja: "驛舍", note: "" },
  { hangul: "철도", roman: "CH'ŎLDO", en: "railway", hanja: "鐵道", note: "" },
  { hangul: "선", roman: "SŎN", en: "line (railway)", hanja: "線", note: "Suffixed: 평라선 = P'yŏngra Line." },
  { hangul: "지하철도", roman: "CHIHA-CH'ŎLDO", en: "metro (underground railway)", hanja: "地下鐵道", note: "Usually shortened to 지하철." },
  { hangul: "승강대", roman: "SŬNGGANGDAE", en: "platform", hanja: "乘降臺", note: "" },
  { hangul: "궤도", roman: "KWEDO", en: "track / gauge", hanja: "軌道", note: "" },
  { hangul: "차표", roman: "CH'AP'YO", en: "ticket", hanja: "車票", note: "" }
];

const POSTS_RECENT = [
  { t: "On the gauge-change apron at Tumangang",        kr: "두만강역 궤도변경대에서", d: "2026·04·19" },
  { t: "A morning in the P'yŏngyang Metro workshop",    kr: "평양지하철도 공작장의 아침", d: "2026·04·11" },
  { t: "Electrification of the Manp'o Line, 1985–88",   kr: "만포선 전화사업, 1985–88", d: "2026·03·28" },
  { t: "The disappearing steam of Hamhŭng shed",         kr: "함흥기관고의 사라지는 증기", d: "2026·03·14" },
  { t: "Timetable notations, translated",               kr: "시간표 기호 해설",            d: "2026·02·22" }
];

const TAGS = [
  ["electric", "lg"], ["locomotive", "lg"], ["P'yŏngyang", "md"], ["metro", "md"],
  ["steam", "sm"], ["Red Flag", "md"], ["Manp'o", "sm"], ["signals", "sm"],
  ["stations", "lg"], ["timetable", "sm"], ["electrification", "md"], ["freight", "md"],
  ["heritage", "sm"], ["coal", "sm"], ["1970s", "sm"], ["DPRK-built", "lg"],
  ["import", "sm"], ["Bo′Bo′Bo′", "sm"], ["3 kV DC", "md"]
];

const CATEGORIES = [
  { en: "Locomotives", kr: "기관차", count: 48 },
  { en: "Rolling stock", kr: "차량", count: 31 },
  { en: "Lines & routes", kr: "선·로선", count: 22 },
  { en: "Stations", kr: "역사", count: 64 },
  { en: "Electrification", kr: "전화사업", count: 17 },
  { en: "Signals & operation", kr: "신호·운전", count: 13 },
  { en: "Heritage & preservation", kr: "유산·보존", count: 9 },
  { en: "Timetables", kr: "시간표", count: 28 }
];

const ARCHIVE_YEARS = [
  ["2026", 12], ["2025", 48], ["2024", 57], ["2023", 41], ["2022", 29],
  ["2021", 18], ["2020", 9],  ["2019", 14], ["2018", 11]
];

Object.assign(window, { LOCOMOTIVES, LINES, STATIONS_FEATURED, GLOSSARY, POSTS_RECENT, TAGS, CATEGORIES, ARCHIVE_YEARS });
